// This file will be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/lib/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      blog_posts: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          title: string
          summary: string
          date: string
          tags: string[]
          content: Json | null
          slug: string
          published: boolean
          author_id: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          title: string
          summary: string
          date: string
          tags?: string[]
          content?: Json | null
          slug: string
          published?: boolean
          author_id?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          title?: string
          summary?: string
          date?: string
          tags?: string[]
          content?: Json | null
          slug?: string
          published?: boolean
          author_id?: string | null
        }
      }
      profiles: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          name: string
          date: string | null
          content: Json
          is_active: boolean
          avatar_url: string | null
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          name: string
          date?: string | null
          content?: Json
          is_active?: boolean
          avatar_url?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          name?: string
          date?: string | null
          content?: Json
          is_active?: boolean
          avatar_url?: string | null
        }
      }
      system_info: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          version: string
          name: string
          description: string | null
          wallpaper: string | null
          theme: Json
          config: Json
          is_active: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          version: string
          name?: string
          description?: string | null
          wallpaper?: string | null
          theme?: Json
          config?: Json
          is_active?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          version?: string
          name?: string
          description?: string | null
          wallpaper?: string | null
          theme?: Json
          config?: Json
          is_active?: boolean
        }
      }
    }
  }
}
